#!/bin/bash
# Matrix Online Authentication Fix Application Script

echo "Matrix Online Authentication Fix"
echo "================================"
echo ""
echo "This script will apply the authentication deadlock fix."
echo "The fix makes the server send an initial packet after connection,"
echo "which triggers the client to start the authentication sequence."
echo ""
echo "Files involved:"
echo "- Source: AuthSocket_FixedV3.cs (the fix)"
echo "- Target: /Users/pascaldisse/Downloads/mxo/mxo-hd-nov2020/hds/auth/AuthSocket.cs"
echo ""
echo "To apply the fix, run:"
echo ""
echo "sudo cp /Users/pascaldisse/Downloads/mxo/AuthSocket_FixedV3.cs \\"
echo "        /Users/pascaldisse/Downloads/mxo/mxo-hd-nov2020/hds/auth/AuthSocket.cs"
echo ""
echo "Then rebuild the server:"
echo ""
echo "cd /Users/pascaldisse/Downloads/mxo/mxo-hd-nov2020"
echo "msbuild /p:Configuration=Debug /p:Platform=x86"
echo ""
echo "The fix adds these lines after accepting a connection:"
echo "- byte[] initialPacket = { 0x00, 0x04, 0x00, 0x05, 0x00, 0x01 };"
echo "- ClientStream.Write(initialPacket, 0, initialPacket.Length);"
echo ""
echo "This sends opcode 0x05 which should trigger the client to respond."